import type { AiOutputLanguage } from "./outputLanguage";

type IdentificationExamples = {
  beer: string;
  casserole: string;
  milk: string;
  bread: string;
  butter: string;
  frozenPizza: string;
  cola: string;
  productsForCasserole: string;
  ingredientsForPizza: string;
  ingredientsForLasagne: string;
  forBbq: string;
  forPancakes: string;
  forBurgers: string;
  weekendShopping: string;
  frozenLasagne: string;
  casseroleAndPizzaIngredients: string;
  frozenPizzaAndLasagneIngredients: string;
  andConjunction: string;
};

const EXAMPLES: Record<AiOutputLanguage, IdentificationExamples> = {
  pl: {
    beer: "Piwo",
    casserole: "Zapiekanka",
    milk: "Mleko",
    bread: "Chleb",
    butter: "Masło",
    frozenPizza: "Pizza mrożona",
    cola: "Cola",
    productsForCasserole: "Produkty na zapiekankę",
    ingredientsForPizza: "Składniki do pizzy",
    ingredientsForLasagne: "Składniki na lasagne",
    forBbq: "Na grilla",
    forPancakes: "Na naleśniki",
    forBurgers: "Na burgery",
    weekendShopping: "Zakupy na weekend",
    frozenLasagne: "Lasagne mrożona",
    casseroleAndPizzaIngredients: "Zapiekanka, składniki na pizzę",
    frozenPizzaAndLasagneIngredients: "Pizza mrożona, składniki na lasagne",
    andConjunction: "i",
  },
  en: {
    beer: "Beer",
    casserole: "Casserole",
    milk: "Milk",
    bread: "Bread",
    butter: "Butter",
    frozenPizza: "Frozen pizza",
    cola: "Cola",
    productsForCasserole: "Products for casserole",
    ingredientsForPizza: "Ingredients for pizza",
    ingredientsForLasagne: "Ingredients for lasagne",
    forBbq: "For BBQ",
    forPancakes: "For pancakes",
    forBurgers: "For burgers",
    weekendShopping: "Weekend shopping",
    frozenLasagne: "Frozen lasagne",
    casseroleAndPizzaIngredients: "Casserole, ingredients for pizza",
    frozenPizzaAndLasagneIngredients: "Frozen pizza, ingredients for lasagne",
    andConjunction: "and",
  },
  de: {
    beer: "Bier",
    casserole: "Auflauf",
    milk: "Milch",
    bread: "Brot",
    butter: "Butter",
    frozenPizza: "Tiefkühlpizza",
    cola: "Cola",
    productsForCasserole: "Zutaten für Auflauf",
    ingredientsForPizza: "Zutaten für Pizza",
    ingredientsForLasagne: "Zutaten für Lasagne",
    forBbq: "Für den Grill",
    forPancakes: "Für Pfannkuchen",
    forBurgers: "Für Burger",
    weekendShopping: "Einkauf fürs Wochenende",
    frozenLasagne: "Tiefkühllasagne",
    casseroleAndPizzaIngredients: "Auflauf, Zutaten für Pizza",
    frozenPizzaAndLasagneIngredients: "Tiefkühlpizza, Zutaten für Lasagne",
    andConjunction: "und",
  },
  fr: {
    beer: "Bière",
    casserole: "Gratin",
    milk: "Lait",
    bread: "Pain",
    butter: "Beurre",
    frozenPizza: "Pizza surgelée",
    cola: "Cola",
    productsForCasserole: "Produits pour gratin",
    ingredientsForPizza: "Ingrédients pour pizza",
    ingredientsForLasagne: "Ingrédients pour lasagne",
    forBbq: "Pour le barbecue",
    forPancakes: "Pour les crêpes",
    forBurgers: "Pour les burgers",
    weekendShopping: "Courses du week-end",
    frozenLasagne: "Lasagne surgelée",
    casseroleAndPizzaIngredients: "Gratin, ingrédients pour pizza",
    frozenPizzaAndLasagneIngredients: "Pizza surgelée, ingrédients pour lasagne",
    andConjunction: "et",
  },
  es: {
    beer: "Cerveza",
    casserole: "Gratinado",
    milk: "Leche",
    bread: "Pan",
    butter: "Mantequilla",
    frozenPizza: "Pizza congelada",
    cola: "Cola",
    productsForCasserole: "Productos para gratinado",
    ingredientsForPizza: "Ingredientes para pizza",
    ingredientsForLasagne: "Ingredientes para lasaña",
    forBbq: "Para la parrilla",
    forPancakes: "Para crepes",
    forBurgers: "Para hamburguesas",
    weekendShopping: "Compras del fin de semana",
    frozenLasagne: "Lasaña congelada",
    casseroleAndPizzaIngredients: "Gratinado, ingredientes para pizza",
    frozenPizzaAndLasagneIngredients:
      "Pizza congelada, ingredientes para lasaña",
    andConjunction: "y",
  },
  it: {
    beer: "Birra",
    casserole: "Sformato",
    milk: "Latte",
    bread: "Pane",
    butter: "Burro",
    frozenPizza: "Pizza surgelata",
    cola: "Cola",
    productsForCasserole: "Prodotti per sformato",
    ingredientsForPizza: "Ingredienti per pizza",
    ingredientsForLasagne: "Ingredienti per lasagna",
    forBbq: "Per il barbecue",
    forPancakes: "Per i pancake",
    forBurgers: "Per gli hamburger",
    weekendShopping: "Spesa del weekend",
    frozenLasagne: "Lasagna surgelata",
    casseroleAndPizzaIngredients: "Sformato, ingredienti per pizza",
    frozenPizzaAndLasagneIngredients:
      "Pizza surgelata, ingredienti per lasagna",
    andConjunction: "e",
  },
  cs: {
    beer: "Pivo",
    casserole: "Zapečený pokrm",
    milk: "Mléko",
    bread: "Chléb",
    butter: "Máslo",
    frozenPizza: "Mražená pizza",
    cola: "Cola",
    productsForCasserole: "Produkty na zapečení",
    ingredientsForPizza: "Ingredience na pizzu",
    ingredientsForLasagne: "Ingredience na lasagne",
    forBbq: "Na gril",
    forPancakes: "Na palačinky",
    forBurgers: "Na burgery",
    weekendShopping: "Nákupy na víkend",
    frozenLasagne: "Mražené lasagne",
    casseroleAndPizzaIngredients: "Zapečený pokrm, ingredience na pizzu",
    frozenPizzaAndLasagneIngredients: "Mražená pizza, ingredience na lasagne",
    andConjunction: "a",
  },
  ru: {
    beer: "Пиво",
    casserole: "Запеканка",
    milk: "Молоко",
    bread: "Хлеб",
    butter: "Масло",
    frozenPizza: "Замороженная пицца",
    cola: "Кола",
    productsForCasserole: "Продукты на запеканку",
    ingredientsForPizza: "Ингредиенты для пиццы",
    ingredientsForLasagne: "Ингредиенты для лазаньи",
    forBbq: "На гриль",
    forPancakes: "На блины",
    forBurgers: "На бургеры",
    weekendShopping: "Покупки на выходные",
    frozenLasagne: "Замороженная лазанья",
    casseroleAndPizzaIngredients: "Запеканка, ингредиенты для пиццы",
    frozenPizzaAndLasagneIngredients:
      "Замороженная пицца, ингредиенты для лазаньи",
    andConjunction: "и",
  },
  uk: {
    beer: "Пиво",
    casserole: "Запіканка",
    milk: "Молоко",
    bread: "Хліб",
    butter: "Масло",
    frozenPizza: "Заморожена піца",
    cola: "Кола",
    productsForCasserole: "Продукти на запіканку",
    ingredientsForPizza: "Інгредієнти для піци",
    ingredientsForLasagne: "Інгредієнти для лазаньї",
    forBbq: "На гриль",
    forPancakes: "На млинці",
    forBurgers: "На бургери",
    weekendShopping: "Покупки на вихідні",
    frozenLasagne: "Заморожена лазанья",
    casseroleAndPizzaIngredients: "Запіканка, інгредієнти для піци",
    frozenPizzaAndLasagneIngredients:
      "Заморожена піца, інгредієнти для лазаньї",
    andConjunction: "і",
  },
  be: {
    beer: "Піва",
    casserole: "Запяканка",
    milk: "Малако",
    bread: "Хлеб",
    butter: "Масла",
    frozenPizza: "Марожаная піца",
    cola: "Кола",
    productsForCasserole: "Прадукты на запяканку",
    ingredientsForPizza: "Інгрэдыенты для піцы",
    ingredientsForLasagne: "Інгрэдыенты для лазаньі",
    forBbq: "На грыль",
    forPancakes: "На бліны",
    forBurgers: "На бургеры",
    weekendShopping: "Пакупкі на выхадныя",
    frozenLasagne: "Марожаная лазанья",
    casseroleAndPizzaIngredients: "Запяканка, інгрэдыенты для піцы",
    frozenPizzaAndLasagneIngredients:
      "Марожаная піца, інгрэдыенты для лазаньі",
    andConjunction: "і",
  },
};

/**
 * Shared ITEM IDENTIFICATION rules for ingest proposal builders.
 * Identify candidate shopping items before deriving shoppingContext.
 */
export function buildItemIdentificationBlock(language: AiOutputLanguage): string {
  const ex = EXAMPLES[language];
  return [
    "ITEM IDENTIFICATION (highest priority):",
    "First identify all candidate shopping items explicitly mentioned by the user. Only then infer shoppingContext.",
    "Item identification should be lossless. Do not discard, merge or reinterpret explicitly listed items before extraction is complete.",
    `Unless clear grammatical evidence otherwise, every noun/noun phrase separated by commas or conjunctions (and/or/${ex.andConjunction}/…) = a separate candidate shopping item.`,
    "Do not reinterpret an explicitly listed candidate as shopping context unless surrounding grammar clearly indicates it is not a shopping item.",
    "shoppingContext is derived from the identified items and the overall sentence meaning. It must never change the identified item set.",
    "Theme/occasion only (do NOT invent products) when grammar marks purpose/meal/occasion, e.g.:",
    `- \"${ex.productsForCasserole}\" → theme only`,
    `- \"${ex.ingredientsForPizza}\" / \"${ex.ingredientsForLasagne}\" → theme only`,
    `- \"${ex.forBbq}\" / \"${ex.forPancakes}\" / \"${ex.forBurgers}\" → theme only`,
    `- \"${ex.weekendShopping}\" → theme/occasion only (not a meal)`,
    "Grammar contrast (not \"is this a SKU?\"):",
    `- \"${ex.frozenLasagne}\" → shopping item`,
    `- \"${ex.ingredientsForLasagne}\" → theme only`,
    "Examples:",
    `- \"${ex.beer}, ${ex.casserole}\" → items ${ex.beer} + ${ex.casserole} (do not swallow ${ex.casserole} into title)`,
    `- \"${ex.milk}, ${ex.bread} ${ex.andConjunction} ${ex.butter}\" → 3 items`,
    `- \"${ex.frozenPizza}, ${ex.cola}\" → 2 items`,
    `- \"${ex.casseroleAndPizzaIngredients}\" → item ${ex.casserole}; theme ≈ pizza`,
    `- \"${ex.frozenPizzaAndLasagneIngredients}\" → item ${ex.frozenPizza}; theme ≈ lasagne`,
  ].join("\n");
}
